// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GPTPlugin","status":true,"description":"[RPG Maker MZ] [Version 1.0] [FCV17]","parameters":{"param1":"Hello World","param2":"40"}}
];
